@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwibmFtZSI6IkFkbWluaXN0cmFkb3IiLCJyb2xlIjoiYWRtaW4ifQ.n-O6y4pX8XDK9boLE3vcYkpgyFpCtMlmF9ajzg3d3cM

@URL_BASE=http://localhost/aula/aula-2-2022/autenticacao-jwt

### Obter um token

POST {{URL_BASE}}/auth.php
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}


### Abrindo um recurso qualquer

POST {{URL_BASE}}/resource-example.php
Authorization: {{JWT}}


