@URL=http://localhost/Ecommerce/api

### OBTER TODAS AS produtoS

@JWTUSER=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImVtYWlsIjoib3N2YWxkb25ldG9AZ21haWwuY29tIiwiYWRtaW4iOjB9.jQPemERbiI4SDclw78ghCkrQyQ2fLeK4JU6H8CDFgFY
@JWTADMIN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsImVtYWlsIjoiSGVsb0BnbWFpbC5jb20iLCJhZG1pbiI6MX0.6qkdBGnmXigqg5_mTA9zv3b5Ei0swG_8esFlt8B_UD8

GET {{URL}}/produto/get.php

### ATUALIZAR produto
POST {{URL}}/produto/update.php?id=22
Content-Type: application/json
Authorization: {{JWTADMIN}}
//Authorization: {{JWTUSER}}
    
{
  "nome": "Cachepo Amadeirado",
  "descricao": "Esmaltado",
  "preco": 149.99,
  "quantidade": 5
}

### CRIAR UM produto
POST {{URL}}/produto/create.php/
Content-Type: application/json
Authorization: {{JWTADMIN}}
//Authorization: {{JWTUSER}}

{
  "nome": "Xicara de sapo",
  "descricao": "Contem sapo dentro",
  "preco": 299.00,
  "quantidade": 2,
  "itens": [
      {
      "categoria_id": 29
      }
           ] 
}

### DELETAR UM produto

GET {{URL}}/produto/delete.php?id=22
Authorization: {{JWTADMIN}}
//Authorization: {{JWTUSER}}