@URL=http://localhost/Ecommerce/api

@JWTUSER=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImVtYWlsIjoib3N2YWxkb25ldG9AZ21haWwuY29tIiwiYWRtaW4iOjB9.jQPemERbiI4SDclw78ghCkrQyQ2fLeK4JU6H8CDFgFY
@JWTADMIN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjIsImVtYWlsIjoiSGVsb0BnbWFpbC5jb20iLCJhZG1pbiI6MX0.6qkdBGnmXigqg5_mTA9zv3b5Ei0swG_8esFlt8B_UD8
### OBTER TODAS AS usuarioS

GET {{URL}}/usuario/get.php
Authorization: {{JWTADMIN}}
//Authorization: {{JWTUSER}}

### ATUALIZAR usuario
POST {{URL}}/usuario/update.php?id=45
Content-Type: application/json
Authorization: {{JWTADMIN}}
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDQsImVtYWlsIjoiVXN1YXJpbzFAZ21haWwuY29tIiwiYWRtaW4iOjF9.-eMUhRBtIJ1q5qLP79WzlLDOxK2vB_ClIHq3C2tCmeY
//Token usuario1

    
{
  "nome": "Heloisa",
  "email": "Helo@gmail.com",
  "senha": "1234",
  "nascimento": "1965-07-01",
  "adm": true
}

### CRIAR UM usuario
POST {{URL}}/usuario/create.php/
Content-Type: application/json

{
  "nome": "Usuario3",
  "email": "Usuario3@gmail.com",
  "senha": "1234",
  "nascimento": "2000-12-01",
  "adm": false
}

### DELETAR UM usuario

GET {{URL}}/usuario/delete.php?id=45
Authorization: {{JWTADMIN}}
//Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDQsImVtYWlsIjoiVXN1YXJpbzFAZ21haWwuY29tIiwiYWRtaW4iOjF9.-eMUhRBtIJ1q5qLP79WzlLDOxK2vB_ClIHq3C2tCmeY
//usuario1